In [22]:
def cross_val_index_by_patient(patient_num_beats):
    k = len(patient_num_beats)

    base = 0
    indices = []
    for kk in range(k):
        indices.append([base, base + patient_num_beats[kk]])
        base = base + patient_num_beats[kk] + 1
    return indices

In [23]:
cross_val_index_by_patient([1, 2, 3])

[[0, 1], [2, 4], [5, 8]]

In [3]:
import numpy as np

In [6]:
np.array([1,2,3,1,2])==2

array([False,  True, False, False,  True])

In [60]:
def cross_val_index_by_beat(labels, k, shuffle=True):
    indices = [[] for _ in range(k)]
    n_classes = max(labels) + 1
    for c in range(n_classes):
        indices_in_class = [i for i, label in enumerate(labels) if label == c]
        print(indices_in_class)
        if shuffle:
            random.shuffle(indices_in_class)
        
        increment = len(indices_in_class) // k
        assert increment > 0
        base = 0
        for kk in range(k):
            indices[kk].extend(indices_in_class[base:base + increment])
            base = base + increment
            print("inc", indices[kk])
    return indices

In [61]:
k_folds = cross_val_index_by_beat([1,1,1,0,1,
                                   2,0,2,2,2,
                                   3, 3,3, 0], 3)
k_folds

[3, 6, 13]
inc [6]
inc [13]
inc [3]
[0, 1, 2, 4]
inc [6, 0]
inc [13, 1]
inc [3, 4]
[5, 7, 8, 9]
inc [6, 0, 9]
inc [13, 1, 8]
inc [3, 4, 7]
[10, 11, 12]
inc [6, 0, 9, 12]
inc [13, 1, 8, 10]
inc [3, 4, 7, 11]


[[6, 0, 9, 12], [13, 1, 8, 10], [3, 4, 7, 11]]

In [42]:
for kk in range(3):

    indices_val = k_folds[kk]
    indices_trn = np.ravel([k_folds[i] for i in range(3) if i != kk])
    
    print(indices_val)
    print(indices_trn)
    print()

[0, 5]
[1 7 2 8]

[1, 7]
[0 5 2 8]

[2, 8]
[0 5 1 7]



In [45]:
import random

In [46]:
random.shuffle([1,2,3,4])